### What is Numpy?

Numpy is a numerical computing Python library which provides n-dimensional arrays.

### Why use Numpy?

If we were to implement arrays on python we would make use of lists which are slow to process. Meanwhile Numpy uses C++ on its background to access and manipulate arrays very efficiently on a continuous space.

### Import numpy

Usually numpy is imported under the alias <b>np</b>

In [1]:
import numpy as np
print( 'Version:', np.__version__ )

Version: 1.23.4


### Create arrays

Numpy arrays are of type ndarray. To create an array we have to pass a list/tupples/array-like object-nested sequences to the np.array function.

In [2]:
a = np.array( [1, 2, 3] )# Create array
print( 'type', type(a) )
print( 'shape', a.shape )
print( 'elements:', a[0], a[1], a[2] )
a[0] = 5# Change an element of the array
print( a )

type <class 'numpy.ndarray'>
shape (3,)
elements: 1 2 3
[5 2 3]


### 0-D

0-D arrays are scalar values

In [3]:
a = np.array( 27 )

In [4]:
a.shape

()

In [5]:
a

array(27)

In [6]:
type( a.item() )

int

In [7]:
a

array(27)

### 1-D

List that consists of 0-D arrays

In [8]:
a = np.array( [40,50,60] )

In [9]:
a.shape

(3,)

In [10]:
a

array([40, 50, 60])

In [11]:
print( a )

[40 50 60]


### 2-D

List that consists of 1-D arrays

In [12]:
b = np.array( [ 
                [4,5,6],
                [9,8,7]
    
            ])

In [13]:
print( 'Shape', b.shape )

Shape (2, 3)


In [14]:
b

array([[4, 5, 6],
       [9, 8, 7]])

In [15]:
print( b )

[[4 5 6]
 [9 8 7]]


### 3-D

List that consists of 2-D arrays. In general N-D arrays, list that consists of (N-1)-D arrays.

In [16]:
c = np.array( [ 
    
                [
                    
                    [4,5,6],
                [9,8,7]
                
                ],
    
                [[44,55,66],
                [99,88,77]],
    
            ])
print( c )
print( 'Shape', c.shape )

[[[ 4  5  6]
  [ 9  8  7]]

 [[44 55 66]
  [99 88 77]]]
Shape (2, 2, 3)


Question: Find the position of number 8 in the 3d array

In [17]:
c[ 0 ][ 1 ][ 1  ]

8

### Standard arrays

Numpy also provides many functions to create arrays:

All of zeros

In [18]:
a = np.zeros( (5,5,10) )#,43,5,4,2,4,2,4,3) )
a.shape

(5, 5, 10)

All of ones

In [19]:
b = np.ones( (10,10) )
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Identity matrix

In [20]:
c = np.eye(7)
c

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
d = np.eye(7,10)
d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

Matrix with all its cells sets to a value

In [22]:
e = np.full( (6,8), 4 )
e

array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])

### Index/Access

To iterate through an array use the shape attribute to get its dimensions.

In [23]:
a = np.array( [ [43,42], [10,5], [27,8], [85,52] ] )

print( 'Shape', a.shape )

print('Values')
for i in range( a.shape[0] ):
    for j in range( a.shape[1] ):
        print( a[ i,j ], end=' ' )
    print()

Shape (4, 2)
Values
43 42 
10 5 
27 8 
85 52 


In [24]:
a

array([[43, 42],
       [10,  5],
       [27,  8],
       [85, 52]])

To refer to some cell of matrix a we use a[idx1][idx2]...[idxn] per dimension
or a[idx1,idx2,...,idxn]

In [25]:
a[1][1]

5

In [26]:
a[1,1]

5

### Subarrays

Function np.arange(n) return all numbers from [0,n)

In [27]:
a = np.arange(100).reshape( (10,10) )

In [28]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

To refer to subarrays use the notation below

array[ firstRow:lastRow, firstCol:lastCol, ...  ]

where firstRow:lastRow and firstCol:lastCol are some list

In [29]:
b = a[ 1:4, 1:5 ]

In [30]:
b

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [31]:
c = a[ 1 ]
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
a[1].shape

(10,)

In [33]:
c.shape

(10,)

In [34]:
d = a[1]

In [35]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
d.shape

(10,)

In [37]:
a[ 1:4, 1:5 ] = 50

In [38]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 50, 50, 50, 50, 15, 16, 17, 18, 19],
       [20, 50, 50, 50, 50, 25, 26, 27, 28, 29],
       [30, 50, 50, 50, 50, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Reshape

In [39]:
d = np.arange( 10 ).reshape(  (1,1,1,1,1,1,10)  )
print( d )
print( d.shape )

[[[[[[[0 1 2 3 4 5 6 7 8 9]]]]]]]
(1, 1, 1, 1, 1, 1, 10)


In [40]:
e = d.reshape( (2,5) )

In [41]:
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
e.shape

(2, 5)

In [43]:
d = np.arange(10).reshape( (5,2) )
print( d.shape )
print( d.T.shape )
np.transpose(d).T

(5, 2)
(2, 5)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Exercise: Make use of the function np.tranpose or T attribute of the ndarray object.

$tr(A) = A^{T}$

Write the corresponding code below each comment

In [44]:
a = np.array( [  [2,4,5,2,1], [45,2,45,1,76] ] )

In [45]:
print(a)
a.shape

[[ 2  4  5  2  1]
 [45  2 45  1 76]]


(2, 5)

In [46]:
print( np.transpose(a), np.transpose(a).shape )

[[ 2 45]
 [ 4  2]
 [ 5 45]
 [ 2  1]
 [ 1 76]] (5, 2)


In [47]:
print( a.T, a.T.shape )

[[ 2 45]
 [ 4  2]
 [ 5 45]
 [ 2  1]
 [ 1 76]] (5, 2)


In [48]:
#Create an array of size 2x5
b = np.array( [ [84,284,20,18,423],[8,472,82,582,22] ] )
#print array and its shape
print( 'orig' )
print( b )
print( 'shape', b.shape )
#use np.transpose( array ) or array.T attribute to calculate the tranpose of array
print()
#print tranposed array and its shape
print( 'transposed' )
print( b.T )
print( 'shape', b.T.shape )

orig
[[ 84 284  20  18 423]
 [  8 472  82 582  22]]
shape (2, 5)

transposed
[[ 84   8]
 [284 472]
 [ 20  82]
 [ 18 582]
 [423  22]]
shape (5, 2)


### Minor fix at 1-D arrays

Notice that 1-D arrays have a shape of (N,) instead of (N,1).

In [49]:
a = np.array( [1,2,3] )

In [50]:
a

array([1, 2, 3])

In [51]:
a.T

array([1, 2, 3])

In [52]:
a.T.shape

(3,)

In [53]:
a.T.T.shape

(3,)

Exercise: What do you notice at the result of the tranpose? Is it correct? Justify your answer.

Solution:

When the shape is (N,), the shape of the tranpose cannot be changed to (,N)

First solution:

We could declare the array as 2D, but that would result in a row-vector. If you would like it in column-vector form use .T attribute at its end.

In [54]:
a = np.array( [ [1,2,3] ] )

In [55]:
a

array([[1, 2, 3]])

In [56]:
a.shape

(1, 3)

In [57]:
a.T

array([[1],
       [2],
       [3]])

In [58]:
a.T.shape

(3, 1)

Second solution:
    
Use reshape:
    
a = np.array( [1,2,3] ).reshape( (3,1) )

or

a = np.array( [1,2,3] ).reshape( (-1,1) )

which would automatically replace -1 with 3 since it the only unknown variable.

In [59]:
a = np.array( [1,2,3] ).reshape( (-1,1) )

In [60]:
a

array([[1],
       [2],
       [3]])

In [61]:
a.shape

(3, 1)

In [62]:
a.T

array([[1, 2, 3]])

In [63]:
a.T.shape

(1, 3)

### Copy

In [64]:
a = np.array( [ [1,2,3,4,5], [1,2,3,4,5] ] )
b = a

In [65]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [66]:
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [67]:
a[0,1] = 7

In [68]:
a

array([[1, 7, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [69]:
b

array([[1, 7, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [70]:
b = a.copy()

In [71]:
a[0,1] = 10

In [72]:
a

array([[ 1, 10,  3,  4,  5],
       [ 1,  2,  3,  4,  5]])

In [73]:
b

array([[1, 7, 3, 4, 5],
       [1, 2, 3, 4, 5]])

For nested sequences/lists use deepcopy from copy library

In [74]:
from copy import deepcopy

In [75]:
"""
For example
E.x.
    b = [ 
    np.array(...), 
    np.array(...), 
    [ 
        [ 
            [ np.array(...)] ] ], [] ]
            
a = copy(b)
"""

'\nFor example\nE.x.\n    b = [ \n    np.array(...), \n    np.array(...), \n    [ \n        [ \n            [ np.array(...)] ] ], [] ]\n            \na = copy(b)\n'

### Stack

In [76]:
a = np.array( [ [1,2,3,4,5], [1,2,3,4,5] ] )

In [77]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

Horizontal

In [78]:
np.concatenate( [ a, a ], axis=0 )

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [79]:
np.concatenate( [a,a], axis=1 )

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

Exercise:

$ B = \begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9
\end{bmatrix}
$

Create matrix $[ I_{3} B ]$

Solution:

Note that B is the tranposed array of

$ B^{T} = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$


which could be created by the np.arange function

B = np.arange(9).reshape( (3,3) ).T + 1

In [80]:
B = np.arange(9).reshape( (3,3) ).T + 1
np.concatenate( [np.eye(3), B], axis=1 )

array([[1., 0., 0., 1., 4., 7.],
       [0., 1., 0., 2., 5., 8.],
       [0., 0., 1., 3., 6., 9.]])

### Split

In [81]:
a = np.arange( 20 ) + 1
b = np.array_split( a, 5 )

In [82]:
b

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]),
 array([17, 18, 19, 20])]

### Random

np.random.random return numbers $\in [0,1)$ 

In [83]:
b = np.random.random( (10,3) )

In [84]:
b

array([[0.93661697, 0.9740024 , 0.19891753],
       [0.45586691, 0.68527909, 0.12606013],
       [0.26945864, 0.28162853, 0.88980168],
       [0.32244811, 0.8445417 , 0.7607869 ],
       [0.63321931, 0.84241212, 0.68983991],
       [0.73074059, 0.32547009, 0.53952848],
       [0.3065416 , 0.54162025, 0.70048167],
       [0.5845178 , 0.77797644, 0.84283312],
       [0.92546431, 0.15146439, 0.13813672],
       [0.56208361, 0.67968036, 0.7869701 ]])

In [85]:
a = np.random.permutation( 10 )[0:3]

In [86]:
b[ a ]

array([[0.45586691, 0.68527909, 0.12606013],
       [0.73074059, 0.32547009, 0.53952848],
       [0.92546431, 0.15146439, 0.13813672]])

### Dtype

Arrays are defined to be within a data type ex. np.float32, np.float64, np.int8, np.int16, np.32, np.in64

In [87]:
a = np.arange(10).reshape( (2,5) )
b = np.array( [ [2.5,3.2], [6.8,8.9] ] )

In [88]:
a.dtype

dtype('int32')

In [89]:
b.dtype

dtype('float64')

In [90]:
c = np.array( [ [2.5,3.2], [6.8,8.9] ], 
             dtype=np.float32 )

In [91]:
c

array([[2.5, 3.2],
       [6.8, 8.9]], dtype=float32)

In [92]:
d = np.array( [ [3,5], [8,13] ], dtype=np.int8 )

In [93]:
d

array([[ 3,  5],
       [ 8, 13]], dtype=int8)

To convert to another datatype use astype function

In [94]:
f = d.astype( np.float64 )

In [95]:
f

array([[ 3.,  5.],
       [ 8., 13.]])

In [96]:
f.dtype

dtype('float64')

### Operations between matrices

Addition

In [97]:
import numpy as np
a = np.arange(25).reshape( (5,5) )

In [98]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

As you would expect the additon is executed elemtwise

In [99]:
a + a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

Likewise for subtraction

In [100]:
a - a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Multiplication

Elementwise multiplication

In [101]:
a * a

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [102]:
np.multiply(a,a)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

For matrix multiplication use np.dot

$$AxB = C$$

$$NxM \times MxN = NxN$$

In [103]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
np.dot(a,a)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

Matrix x Vector

$$A \times x = b$$
$$ (N \times m) \times (M\times1) = N \times 1$$

In [105]:
x = np.array( [0,5,10,15,20] ).reshape( (-1,1) )

In [106]:
x

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [107]:
np.dot(a, x )

array([[ 150],
       [ 400],
       [ 650],
       [ 900],
       [1150]])

Vector x Vector

In [108]:
x

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

Dot/Inner/Scalar product

$x^{T} \times x$

In [109]:
np.dot(x.T,x)

array([[750]])

Elementwise

In [110]:
np.multiply(x,x)

array([[  0],
       [ 25],
       [100],
       [225],
       [400]])

In [111]:
x * x 

array([[  0],
       [ 25],
       [100],
       [225],
       [400]])

### Broadcast

When there is a mismatch on the array shapes, operation are still possible under certain conditions. For example in the example below the array [4,8,12] is replicated to match the dimension of the matrix its being added to.

![broadcast](img/1.png)

In [112]:
a = np.zeros( (5,5) )

In [113]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [114]:
b = np.array( [1,2,3,4,5] ).reshape( (-1,1) )
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

broadcast per row

In [115]:
a + b.T

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

broadcast per column

In [116]:
a + b.T

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

Exercise: For each cell calculate its percentage per row

In [117]:
a = np.array( [ [1,1,2], [24,42,12], [10,20,30], [80,40,20] ] ).T

In [118]:
a

array([[ 1, 24, 10, 80],
       [ 1, 42, 20, 40],
       [ 2, 12, 30, 20]])

In [119]:
#hint use np.sum( ..., axis=0 ) to get the sum per col

Soluton:

Let v = np.sum( a, axis=0 ) be the sum of each column

v = array([  4,  78,  60, 140])

To calculate the percentage per column we have to make sure v is in row-vector form -> (1,4) and apply the
/ operator with a in order to be broadcasted on each row.

In [120]:
v = np.sum( a, axis=0 ).reshape( (1,-1) )
print( 'V' )
print( v )
print( 'Result' )
print( a / v )

V
[[  4  78  60 140]]
Result
[[0.25       0.30769231 0.16666667 0.57142857]
 [0.25       0.53846154 0.33333333 0.28571429]
 [0.5        0.15384615 0.5        0.14285714]]


### Tile

Instead of broadcasting we could repeat the pattern using the np.tile( array, shape )

In [121]:
a = np.array( [1,2,3] ).reshape( (-1,1) )

In [122]:
a

array([[1],
       [2],
       [3]])

In [123]:
np.tile( a, (1,1) )

array([[1],
       [2],
       [3]])

In [124]:
np.tile( a, (1,10) )

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [125]:
np.tile( a, (3,1) )

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [126]:
np.tile( a, (2,3) )

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### Other

Determinant

In [127]:
a = np.array( [ [10,20], [30,40] ] )
b = np.linalg.det(a)
print(a)

[[10 20]
 [30 40]]


In [128]:
b

-200.0000000000001

Inversion

In [129]:
a = np.array( [ [10,20], [30,40] ] )

In [130]:
b = np.linalg.inv( a )

In [131]:
a

array([[10, 20],
       [30, 40]])

In [132]:
b

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [133]:
b.shape

(2, 2)

In [134]:
np.dot( a, b )

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

Argmax/Argmax

In [135]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [136]:
a[ np.arange(5) ] = a[ np.random.permutation(5) ] 

In [137]:
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

This kind of encoding is known as one-hot vector in machine learning. Instead of zeros and ones it could have real values to represent probabilities. Each row represent its percentage to be classified to a specific category(e.x. 5 columns = 5 classes/categories ). So argmax per row would choose the category that has the maximum probability/value.

In [138]:
np.argmax( a, axis=1 )

array([1, 3, 2, 0, 4], dtype=int64)

##### Where

Given a condition returns the indices per dimension

In [139]:
a = np.arange( 15 ).reshape(3,5)
b = np.where( a <= 5 )

In [140]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [141]:
print( 'X', b[0] )
print( 'Y', b[1] )

X [0 0 0 0 0 1]
Y [0 1 2 3 4 0]
